### ISSUE TITLE
Plugin doesn't install after saying it installed successfully

### ISSUE THREAD

**Issue by skint007** [markwal/OctoPrint-PolarCloud#43] opened 2018-09-06 02:43 UTC
I've been trying to install the plugin multiple and haven't been successful. It says it installed, but I noticed when its finished and asks to restart it says "Installed Unknown" instead of Polar Cloud.

Here is what it looks like:
https://www.dropbox.com/s/qnmrfgczchlfckr/Install_Polar3d.png?dl=0

**Comment by AbuKareem** [comment] 2018-09-06 11:47
I'm having the exact same problem
![screenshot 14](https://user-images.githubusercontent.com/16438737/45155475-d0963e80-b1e3-11e8-8d6e-c22cddd2e47c.png)

**Comment by AbuKareem** [comment] 2018-09-06 13:51
### Update ### 
i followed these commands from issue https://github.com/markwal/OctoPrint-PolarCloud/issues/38
source ~/oprint/bin/activate
pip uninstall cryptography
pip uninstall cffi
pip uninstall Pillow
pip install cffi=1.11.5
pip install cryptography==2.2.2
pip install Pillow

now the install shows the plugin name
but it is still not showing in the plugins menu
and when searching in plugins manager it shows it is not installed and gives the option to install

![screenshot 15](https://user-images.githubusercontent.com/16438737/45161620-f4ae4b80-b1f4-11e8-9542-89fd3087199c.png)

**Comment by AbuKareem** [comment] 2018-09-06 14:04
### Update #2 ### 
after the first installation reverted (cryptography) to 2.2.2 
and trying to install the plugin again (because it's not showing) the message after installation displayed the name as unknown 
so perhaps the issue is with the cryptography version that the plugin is using?

**Comment by stefanuc111** [comment] 2018-09-26 20:52
I've the same problem, with octoprint installed in the orange pi lite

**Comment by AndrewRees** [comment] 2018-12-12 23:23
I am experiencing the same problem on OctoPrint Version 1.3.10 / OctoPi Version 0.14.0.

**Comment by markhurlburt** [comment] 2018-12-17 04:04
I'm running into this as well!

**Comment by NovaViper** [comment] 2019-02-19 16:54
Same issue, happened on OctoPrint 1.3.0 and 1.3.10

**Comment by vmorrisPolar** [comment] 2020-12-17 18:38
This issue should have been fixed in subsequent releases.

**Closed as completed by vmorrisPolar** 2020-12-17 18:38 UTC
